# Generated by Django 4.2.4 on 2023-08-25 07:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_attachements"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
