# Generated by Django 4.2.4 on 2023-08-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="attachement",
        ),
        migrations.CreateModel(
            name="StoryAttachement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attachment", models.CharField(max_length=100)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="stories.story",
                    ),
                ),
            ],
        ),
    ]
