# Generated by Django 4.2.4 on 2023-08-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0002_remove_story_attachement_storyattachement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="storyattachement",
            old_name="attachment",
            new_name="url",
        ),
    ]
