# Generated by Django 4.2.4 on 2023-08-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
