# Generated by Django 4.2.4 on 2023-08-24 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="timestamp",
        ),
    ]
