# Generated by Django 4.2.4 on 2023-08-25 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0002_remove_follow_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="follow",
            old_name="following",
            new_name="user_id",
        ),
    ]
