# Generated by Django 4.2.4 on 2023-08-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("followers", "0003_rename_following_follow_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="follow",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
    ]
